INSERT INTO expenses (description, amount, category, userId, createdAt) VALUES
('Weekly grocery shopping', 75.40, 'Groceries', 5, NOW() - INTERVAL '12 days'),
('Monthly electricity bill', 92.15, 'Utilities', 25, NOW() - INTERVAL '45 days'),
('Sushi dinner with friends', 58.00, 'Leisure', 5, NOW() - INTERVAL '2 days'),
('Wireless noise-canceling headphones', 199.99, 'Electronics', 25, NOW() - INTERVAL '88 days'),
('Cotton slim-fit t-shirt', 24.50, 'Clothing', 5, NOW() - INTERVAL '15 days'),
('General medical checkup', 65.00, 'Health', 25, NOW() - INTERVAL '110 days'),
('Netflix monthly subscription', 15.99, 'Leisure', 5, NOW() - INTERVAL '30 days'),
('Fresh fruit and vegetables', 31.20, 'Groceries', 25, NOW() - INTERVAL '5 days'),
('Leather shoe repair', 15.00, 'Others', 5, NOW() - INTERVAL '60 days'),
('Mechanical gaming keyboard', 110.00, 'Electronics', 25, NOW() - INTERVAL '22 days'),
('Quarterly water bill', 42.10, 'Utilities', 5, NOW() - INTERVAL '95 days'),
('Nike running shoes', 85.00, 'Clothing', 25, NOW() - INTERVAL '10 days'),
('Vitamin C and D supplements', 22.40, 'Health', 5, NOW() - INTERVAL '40 days'),
('Movie night and popcorn', 28.50, 'Leisure', 25, NOW() - INTERVAL '67 days'),
('Fiber optic internet bill', 55.00, 'Utilities', 5, NOW() - INTERVAL '14 days'),
('Professional dental cleaning', 75.00, 'Health', 25, NOW() - INTERVAL '102 days'),
('27-inch 4K monitor', 280.00, 'Electronics', 5, NOW() - INTERVAL '55 days'),
('Organic meat and poultry', 45.30, 'Groceries', 25, NOW() - INTERVAL '8 days'),
('Blue denim jeans', 49.99, 'Clothing', 5, NOW() - INTERVAL '73 days'),
('Birthday gift for colleague', 30.00, 'Others', 25, NOW() - INTERVAL '3 days'),
('Morning latte at Starbucks', 6.50, 'Leisure', 5, NOW() - INTERVAL '12 days'),
('Extended RGB mouse pad', 25.00, 'Electronics', 25, NOW() - INTERVAL '115 days'),
('Laundry detergent and supplies', 18.75, 'Groceries', 5, NOW() - INTERVAL '28 days'),
('Natural gas heating bill', 68.00, 'Utilities', 25, NOW() - INTERVAL '38 days'),
('Whey protein powder', 45.00, 'Health', 5, NOW() - INTERVAL '91 days'),
('Heavy winter parka', 145.00, 'Clothing', 25, NOW() - INTERVAL '105 days'),
('Live concert tickets', 120.00, 'Leisure', 5, NOW() - INTERVAL '48 days'),
('Premium HDMI cable', 15.99, 'Electronics', 25, NOW() - INTERVAL '19 days'),
('Fresh bakery bread', 8.20, 'Groceries', 5, NOW() - INTERVAL '1 day'),
('Airport shuttle taxi', 45.00, 'Others', 25, NOW() - INTERVAL '82 days'),
('Spotify Family plan', 16.99, 'Leisure', 5, NOW() - INTERVAL '60 days'),
('Emergency pipe repair', 180.00, 'Utilities', 25, NOW() - INTERVAL '77 days'),
('Flu and cold medicine', 12.50, 'Health', 5, NOW() - INTERVAL '21 days'),
('Fresh salmon and seafood', 38.60, 'Groceries', 25, NOW() - INTERVAL '33 days'),
('Fast wall charger', 29.00, 'Electronics', 5, NOW() - INTERVAL '44 days'),
('Formal white shirt', 40.00, 'Clothing', 25, NOW() - INTERVAL '119 days'),
('Friday night pizza delivery', 26.50, 'Leisure', 5, NOW() - INTERVAL '6 days'),
('Charity donation', 25.00, 'Others', 25, NOW() - INTERVAL '52 days'),
('Cereal and milk stock', 14.80, 'Groceries', 5, NOW() - INTERVAL '16 days'),
('Mobile phone plan', 50.00, 'Utilities', 25, NOW() - INTERVAL '89 days'),
('Polarized sunglasses', 75.00, 'Clothing', 5, NOW() - INTERVAL '101 days'),
('Cough syrup', 10.20, 'Health', 25, NOW() - INTERVAL '11 days'),
('New AAA game pre-order', 69.99, 'Electronics', 5, NOW() - INTERVAL '27 days'),
('Bowling with coworkers', 42.00, 'Leisure', 25, NOW() - INTERVAL '93 days'),
('Extra virgin olive oil', 18.00, 'Groceries', 5, NOW() - INTERVAL '4 days'),
('Health insurance premium', 120.00, 'Health', 25, NOW() - INTERVAL '58 days'),
('Smart LED light bulbs', 35.00, 'Utilities', 5, NOW() - INTERVAL '70 days'),
('Wool scarf and gloves', 28.00, 'Clothing', 25, NOW() - INTERVAL '112 days'),
('Subscription to Notion', 10.00, 'Electronics', 5, NOW() - INTERVAL '25 days'),
('Service tip at bar', 5.00, 'Others', 25, NOW() - INTERVAL '13 days'),
('Party snacks and drinks', 45.00, 'Groceries', 5, NOW() - INTERVAL '39 days'),
('Anniversary dinner', 135.00, 'Leisure', 25, NOW() - INTERVAL '81 days'),
('Digital infrared thermometer', 19.50, 'Health', 5, NOW() - INTERVAL '98 days'),
('Emergency electrician fix', 200.00, 'Utilities', 25, NOW() - INTERVAL '41 days'),
('USB-C multi-port hub', 45.00, 'Electronics', 5, NOW() - INTERVAL '50 days'),
('Cotton socks pack', 15.00, 'Clothing', 25, NOW() - INTERVAL '63 days'),
('Gelato dessert', 7.50, 'Leisure', 5, NOW() - INTERVAL '2 days'),
('Assorted cheese board', 29.50, 'Groceries', 25, NOW() - INTERVAL '7 days'),
('Parking fine payment', 50.00, 'Others', 5, NOW() - INTERVAL '108 days'),
('Portable power bank', 39.00, 'Electronics', 25, NOW() - INTERVAL '99 days'),
('Gym membership fee', 40.00, 'Health', 5, NOW() - INTERVAL '17 days'),
('Mineral water crates', 12.00, 'Groceries', 25, NOW() - INTERVAL '29 days'),
('Professional haircut', 35.00, 'Others', 5, NOW() - INTERVAL '46 days'),
('Adobe Creative Cloud', 52.99, 'Electronics', 25, NOW() - INTERVAL '72 days'),
('Brown leather loafers', 110.00, 'Clothing', 5, NOW() - INTERVAL '86 days'),
('Coffee bean supply', 22.00, 'Groceries', 25, NOW() - INTERVAL '54 days'),
('Heating gas refill', 75.00, 'Utilities', 5, NOW() - INTERVAL '118 days'),
('Therapeutic massage', 65.00, 'Health', 25, NOW() - INTERVAL '23 days'),
('Drinks at rooftop bar', 55.00, 'Leisure', 5, NOW() - INTERVAL '9 days'),
('Laptop sleeve case', 25.00, 'Electronics', 25, NOW() - INTERVAL '31 days'),
('Eggs and dairy products', 19.70, 'Groceries', 5, NOW() - INTERVAL '43 days'),
('Gym workout shorts', 32.00, 'Clothing', 25, NOW() - INTERVAL '66 days'),
('Data science textbook', 55.00, 'Others', 5, NOW() - INTERVAL '92 days'),
('PC hardware repair', 95.00, 'Electronics', 25, NOW() - INTERVAL '51 days'),
('Fast food lunch', 14.50, 'Leisure', 5, NOW() - INTERVAL '18 days'),
('Pasta and grains', 23.00, 'Groceries', 25, NOW() - INTERVAL '36 days'),
('Electric toothbrush heads', 21.00, 'Health', 5, NOW() - INTERVAL '75 days'),
('Smart desk lamp', 49.00, 'Electronics', 25, NOW() - INTERVAL '114 days'),
('Thermal base layer', 26.00, 'Clothing', 5, NOW() - INTERVAL '20 days'),
('Highway toll charges', 12.50, 'Others', 25, NOW() - INTERVAL '103 days'),
('Amazon Prime renewal', 14.99, 'Leisure', 5, NOW() - INTERVAL '42 days'),
('Distilled water jugs', 5.50, 'Groceries', 25, NOW() - INTERVAL '59 days'),
('Pain relief pills', 9.00, 'Health', 5, NOW() - INTERVAL '84 days'),
('Craft beer six-pack', 19.50, 'Leisure', 25, NOW() - INTERVAL '97 days'),
('Printer ink cartridges', 60.00, 'Electronics', 5, NOW() - INTERVAL '106 days'),
('Knitted wool hat', 18.00, 'Clothing', 25, NOW() - INTERVAL '35 days'),
('Roasted chicken', 12.50, 'Groceries', 5, NOW() - INTERVAL '49 days'),
('Plumber faucet repair', 85.00, 'Utilities', 25, NOW() - INTERVAL '62 days'),
('Art museum ticket', 15.00, 'Leisure', 5, NOW() - INTERVAL '78 days'),
('Yoga class session', 25.00, 'Health', 25, NOW() - INTERVAL '87 days'),
('Bluetooth ergonomic mouse', 35.00, 'Electronics', 5, NOW() - INTERVAL '111 days'),
('Energy drinks pack', 18.00, 'Groceries', 25, NOW() - INTERVAL '56 days'),
('Silk necktie', 45.00, 'Clothing', 5, NOW() - INTERVAL '69 days'),
('Express courier shipping', 12.50, 'Others', 25, NOW() - INTERVAL '47 days'),
('Lunch salad bowl', 13.50, 'Leisure', 5, NOW() - INTERVAL '32 days'),
('Mixed nuts and berries', 16.00, 'Groceries', 25, NOW() - INTERVAL '94 days'),
('Herbal health tea', 14.00, 'Health', 5, NOW() - INTERVAL '109 days'),
('Phone screen protector', 12.00, 'Electronics', 25, NOW() - INTERVAL '71 days'),
('Winter wool socks', 11.00, 'Clothing', 5, NOW() - INTERVAL '80 days'),
('Self-service laundry', 8.00, 'Others', 25, NOW() - INTERVAL '24 days');